### ISSUE TITLE
How to use cakephp pagination using this API

### ISSUE THREAD

**Issue by priti-technomile** [voycey/Salesforce-Enterprise-API-CakePHP-2.x-Plugin#3]
How do I use $this->Paginator->paginate(), using this API. I have more than 2000 records. I need the count of all records (say 5000) while displaying in my .ctp page. I also encountered "MALFORMED_QUERY: SELECT COUNT (Id) FROM <tablename>" error while using cakephp pagination. Any help would be of great use.

Thank you.

**Comment by voycey** [comment]
You should be able to do find('count') on the datasource to get the count.

I cant say I have ever used Pagination with this, you might need to create
a custom pagination method to use with it but I dont see why Pagination
wouldnt work as is to be honest as it uses cakePHP find methods.

Can you post the code you are using for Pagination and ill see if can see
anything immediately wrong with it?

**Comment by priti-technomile** [comment]
Hey Voycey,

Thank you for the help.

In my controller I was trying to do -- $this->loadModel('Salesforce.SalesforceItem'); echo $count = $this->SalesforceItem->find('count'); I was getting MALFORMED_QUERY: SELECT COUNT (Id) FROM Item__c WHERE ^ ERROR at Row:1:Column:36 unexpected token: '' error. 

When I peeped into the "\app\Model\Datasource\SalesforceSource.php", I found that in  function read approximately on line 246 the condition is -- 

if($queryData['fields'] === 'COUNT') {	
$sfq = "SELECT COUNT (Id) FROM {$model->name} WHERE " . implode(" AND ", $conditions);
$results = $this->query($sfq);
return array(array(array('count' => $results[0]['any']['expr0'])));
}
For me the $conditions array was empty and so was returning MALFORMED_QUERY error. All I did is check if the $conditions array is not empty -- 
if($queryData['fields'] === 'COUNT') {
	if(count($conditions) > 0) {
	   $sfq = "SELECT COUNT (Id) FROM {$model->name} WHERE " . implode(" AND ", $conditions);
	} else {
		$sfq = "SELECT COUNT (Id) FROM {$model->name}";
	}
        $results = $this->query($sfq);
        return array(array(array('count' => $results[0]['any']['expr0'])));
}
It is working for me now. Thanks for the API.

**Comment by voycey** [comment]
If you submit a pull request for that Ill merge it in :)

On 6 January 2015 at 19:25, priti-technomile <notifications@github.com>
wrote:

> Hey Voycey,
>
> Thank you for the help.
>
> In my controller I was trying to do --
> $this->loadModel('Salesforce.SalesforceItem'); echo $count =
> $this->SalesforceItem->find('count'); I was getting MALFORMED_QUERY: SELECT
> COUNT (Id) FROM Item__c WHERE ^ ERROR at Row:1:Column:36 unexpected token:
> '' error.
>
> When I peeped into the "\app\Model\Datasource\SalesforceSource.php", I
> found that in function read approximately on line 246 the condition is --
>
> if($queryData['fields'] === 'COUNT') {
>
> $sfq = "SELECT COUNT (Id) FROM {$model->name} WHERE " . implode(" AND ",
> $conditions);
> $results = $this->query($sfq);
> return array(array(array('count' => $results[0]['any']['expr0'])));
> }
> For me the $conditions array was empty and so was returning
> MALFORMED_QUERY error. All I did is check if the $conditions array is not
> empty --
> if($queryData['fields'] === 'COUNT') {
> if(count($conditions) > 0) {
> $sfq = "SELECT COUNT (Id) FROM {$model->name} WHERE " . implode(" AND ",
> $conditions);
> } else {
> $sfq = "SELECT COUNT (Id) FROM {$model->name}";
> }
> $results = $this->query($sfq);
> return array(array(array('count' => $results[0]['any']['expr0'])));
> }
> It is working for me now. Thanks for the API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voycey/Salesforce-Enterprise-API-CakePHP-2.x-Plugin/issues/3#issuecomment-68838374>
> .
>



-- 
__
Mob: (+61) 0481 301 640
Skype: daniel.voyce
Twitter: www.twitter.com/voycey

**Comment by priti-technomile** [comment]
Hey Voycey,

I hope I could not do the pull request as expected. Please do the changes if you think they are correct.

Again thank you for the API.

Regards,
Priti
