### ISSUE TITLE
CakePHP 3.1 Compatibility 

### ISSUE THREAD

**Issue by velkymx** [voycey/Salesforce-Enterprise-API-CakePHP-2.x-Plugin#4]
Any plans to update this to work with the new version of cakephp?

**Comment by voycey** [comment]
Possibly in the future, I could actually do with it being compatible with 3.x but it isn't a simple upgrade, it would have to be a complete rewrite and I don't currently have time to do it.

**Comment by voycey** [comment]
Just an FYI - I am currently working on this, it isn't as simple as a single datasource file it requires drivers and dialects to be written to be compatible with SOQL. I hope to get an alpha version out in the coming week

**Comment by velkymx** [comment]
I'm going to give it a shot using only their RESTful API. I'll keep you posted.

**Comment by voycey** [comment]
I chose not to use it for some reason when I first started, I think it is mainly because SOQL fit so naturally into a Cake2 datasource and keeping it as close to SQL as possible was the main goal for me, im sure you could create a pretty simple interface if you only need a small integration using REST.

**Comment by voycey** [comment]
Dont know how you are getting on with your REST api @velkymx 

But I have started this:
https://github.com/voycey/cakephp-salesforce

I have literally just got it to where it is today, ill be working on it the rest of the week and probably for a little while in the future as it will form a main part of the site I'm doing - still needs a fair amount of work but if you want to get involved in it then feel free :)

**Comment by velkymx** [comment]
I went with their PHP tool kit for Oauth. Once I had the token it was extremely easy to interface via their v35 rest api.

**Comment by voycey** [comment]
Cool, 

I was looking into moving this plugin to REST but there are a few things that wouldn't be as easy are they are now, My 3.x plugin is now working and makes use of SQL Dialects (which Salesforce has its own one) and the Eager Loader + all the validation you get from usual models.

Have you got any code posted for how you did it with REST? Are you using the HTTP client and then processing the data that way?
